### ISSUE TITLE
Server down: "Failed to connect: 0"?

### ISSUE THREAD

**Issue by 10w73** [b2un0/pyload-hooks#2]
http://95.85.62.143/pyControlPush/push.php returns "Failed to connect: 0" and push won't work. Is there a problem with your server?

**Comment by Cseb87** [comment]
Me too

**Comment by b2un0** [comment]
i informed already the pyLoad iOS App developer. he will look at this soon.

Note: i only rewritten this plugin for latest pyLoad updates - so the push server are the same as before from the original pyLoad iOS App developer. :)

**Comment by mathiasnagler** [comment]
I updated the certificate on my server. Could you please try if the issues is fixed now?

**Comment by b2un0** [comment]
fixed by @mathiasnagler
